### ISSUE TITLE
need more improvements to use it

### ISSUE THREAD

**Issue by kunapuli09** [caioquirino/docker-cloudera-quickstart#1] opened 2014-12-27 15:19 UTC
I have attempted this install on ESXI5.5 VM with Ubuntu14.04 4MB RAM and 100G disk space. 
1.5G image download took an hour
install kind of stuck at history server
map-reduce is not installed
can't attach to docker as it hangs for ever
no instructions on how to access cloudera services
First of all I am trying to understand if VM is a good option for me to install this docker image?

**Comment by caioquirino** [comment] 2015-01-14 02:31
Hi @Kunapuli09! Thank you for collaborating!
I am trying to reduce the download size, but some CDH's packages are very large...
Are you using the Docker Hub's version?
I will provide a better documentation and instructions soon.

I think that the map-reduce is installed... Have you tried to use it? Please help-me to investigate.

The best option is to avoid the VM overhead, but you can install if there's the only option.

Thank you and please continue using and collaborating! You're welcome!

**Comment by zzswang** [comment] 2015-01-20 11:37
Thanks for your work, I'm working on this image...

It would be awesome if there is a quick start doc.

**Comment by zzswang** [comment] 2015-01-21 03:19
There is an error in the log

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/zookeeper/KeeperException
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
    at java.lang.Class.getMethod0(Class.java:2856)
    at java.lang.Class.getMethod(Class.java:1668)
    at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.KeeperException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
- Failed to start HBase master daemon. Return value: 1

**Comment by caioquirino** [comment] 2015-03-07 19:30
Thank you @arnaud-bailly for your solution!
I've merged with your fork and now the Docker Hub is building the new image.
@zzswang and @kunapuli09 You can test with the new version please?

**Closed as completed** 2015-03-12 01:37 UTC

**Comment by caioquirino** [comment] 2015-03-12 01:39
Hi guys, I closed this issue as most of the feedbacks of this issue are resolved. If you experience any new problem, please open a new issue.
Thanks for all!
